### ISSUE TITLE
Place window objects

### ISSUE THREAD

**Issue by ajwinter** [NREL/openstudio-geometry-editor#17]

**Comment by devKate** [comment]
Could we go over the desired behavior here?

**Comment by bgschiller** [comment]
When I'm placing a window, it needs to be on an existing edge. Are there any restrictions about where it goes on the edge? Does it's vertex need to be on a grid point?

Does the vertex_id in a window refer to the middle of the window, so it should extend width/2 to either side of that vertex?

**Comment by bgschiller** [comment]
Do we want to enforce that a window's bounds must be smaller than the edge it sits on?

**Comment by bgschiller** [comment]
Also, I thought windows were tied to an *edge*, but in the schema it looks like they're tied to a vertex? What if that vertex is associated with multiple edges? Seems like we'd be better off with something like

```
{
    window_defn_id: "12",
    edge_id: "14",
    location_on_edge: 0.43, // meaning, 43% of the way from start to end.
}
```

I'm just thinking we need a reference to the edge.

**Comment by macumber** [comment]
Updated the schema here: https://github.com/NREL/openstudio-geometry-editor/commit/1ae3627d0cd735bcff4f2cfe9dd2b388e7c07e92

Windows can go anywhere on the edge except they should not be placed on a vertex because that makes it difficult to tell which edge it is on as each vertex is shared by multiple edges.  I think that we should not try to make the windows interact with the grid to start with.  It would be useful to compute the distance along the edge and show that as the user is placing the component, maybe show the distance to the start and to the end of the edge?  In the future, we might snap these distances to a multiple of the grid spacing.

There is no check that the window is fully contained on the edge.  The full extent of the window should be shown visually, the user is responsible to make sure the window is properly placed.

**Comment by macumber** [comment]
If an edge is deleted, then windows on that edge are deleted.  

If an edge is resized, windows should stay in the same absolute location.  If a window's alpha parameter becomes <= 0 or >= 1 the window should be deleted.

If an edge is broken into two pieces (e.g. by inserting a vertex), windows should be moved to the correct edge such that alpha remains <= 0 or >= 1 

(There should be unit tests for all this)

**Comment by shorowit** [comment]
And we are not worrying about a window overlapping another window, right?

**Comment by bgschiller** [comment]
Thanks for the clarifications!

**Comment by macumber** [comment]
Yup, user error if windows overlap

**Comment by bgschiller** [comment]
It's not *always* user error...
![img_20170906_213326](https://user-images.githubusercontent.com/2491257/30144885-36ad6ecc-934b-11e7-894f-6bd88f602d52.jpg)
