### ISSUE TITLE
Change default units to feet (default spacing shows 50 m).

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-geometry-editor#28]

**Comment by devKate** [comment]
@ajwinter, could we go over the meter specific math when you have a moment?

**Comment by ajwinter** [comment]
@devKate I think there's only one spot: in updateMapView() in Map.vue, it needs to check if it's currently meters or feet in order to sync the map zoom level to the grid. You'll see we grab "mPerFt" but don't do anything with it. OpenLayers is always in meters, so if the editor is in feet, we need to convert to meters. I think it's as simple as multiplying deltaX and deltaY by mPerFt in that case.
