### ISSUE TITLE
Numeric feedback when drawing

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-geometry-editor#31]
- [x] Show distance of current line segment for polygons
- [x] Show width + height for rectangles 
- [x] Show area for shapes when drawing

Show as tooltip, ideally at centroid of shape being drawn

**Comment by shorowit** [comment]
Any chance we could do something more compact like this?

![beopt_labels](https://cloud.githubusercontent.com/assets/5861765/26691485/81c538c8-46ba-11e7-85e5-1ad82f60cbd1.png)

BEopt also allows you to see this info when mousing over a space. If the space is rectangular, it shows all of the above info (area, width x height). If the space is not rectangular, it just shows the area. This is particularly handy because if you draw an L shape space using two rectangles, you'd only get the area of each individual rectangle as you draw them, whereas this allows you to get the full area of the space.

**Comment by ajwinter** [comment]
@shorowit Thanks for the feedback! I broke it out into another issue (#54), since it's likely lower priority than some other things right now.
