### ISSUE TITLE
Place Map quirks

### ISSUE THREAD

**Issue by shorowit** [NREL/openstudio-geometry-editor#40]
Search for address: 4500 Squires Circle, Boulder CO

Resulting map (below) doesn't actually show the street. Can this be fixed?
![placemap1](https://cloud.githubusercontent.com/assets/5861765/26368059/bb2c2c20-3fad-11e7-9a31-e80ba2927848.png)

Next, scroll up and to the left to find the street:
![placemap2](https://cloud.githubusercontent.com/assets/5861765/26368062/bd14cc86-3fad-11e7-9ac1-9aaafe025ed6.png)

When you click Done, the map is shifted (below). Can this be fixed?
![placemap3](https://cloud.githubusercontent.com/assets/5861765/26368072/c38e9fec-3fad-11e7-84dd-63cc8cd3b030.png)

**Comment by shorowit** [comment]
So if I place map and pan around, things seem to work much better now. But there are still issues if you zoom.

**Comment by ajwinter** [comment]
The way it works now is:
1. User chooses to set the map on first start.
2. User positions the crosshair on the corner of a building or similar. During this process, they pan and zoom the map.
3. User clicks "Done". The map center of the map stays in the correct place, but the zoom will change to sync up with the grid.

The zoom change to sync up with the grid is a slightly weird user experience, but we felt like it was a lower priority issue. The fix for that is to reverse scale the grid to match the map's zoom level when you click "Done", which is an operation we don't do currently (we always match the map to the grid), so it's non-trivial.

My recommendation is to leave this open, but low priority. Certainly open to other ideas though!

**Comment by ajwinter** [comment]
Created a new issue to log the zoom "jump", since most of this issue is resolved.
