### ISSUE TITLE
Grid does not seem correct in map mode

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-geometry-editor#45]
Here is building when setting map:

![image](https://cloud.githubusercontent.com/assets/1327850/26419839/2ee9b774-407e-11e7-8ba0-f6abfbd28843.png)

Here is building after map:

![image](https://cloud.githubusercontent.com/assets/1327850/26419849/35fff988-407e-11e7-853a-918c5c121bed.png)

**Comment by ajwinter** [comment]
Stories should just count up incrementally.

Spaces should be named by story number and space number, incrementally, like this: Space 1-1, Space 1-2, Space 2-1, Space, 2-2, etc.

**Comment by ajwinter** [comment]
Fixed scaling issue.

@macumber for item 2 above, would it be viable to hide the grid while placing the map? It doesn't seem to have a direct function while doing that, and then it can sync up after the map is placed.

**Comment by shorowit** [comment]
I could imagine users wanting to position the map relative to the grid so that, e.g., a building is perfectly aligned with the grid lines.

**Comment by macumber** [comment]
Alternate approach would be to allow user to shift grid relative to 0, 0 in both x and y

**Comment by ljbrackney** [comment]
Speaking for myself, I could see using grid for a new construction project, but I'm less confident I would want that for a retrofit project where I'd rely more heavily on map features for registration.  My $0.02.

On May 31, 2017, at 5:37 PM, Scott Horowitz <notifications@github.com<mailto:notifications@github.com>> wrote:


I could imagine users wanting to position the map relative to the grid so that, e.g., a building is perfectly aligned with the grid lines.

-

**Comment by macumber** [comment]
I agree with Larry, grid is less useful for tracing.  However, I do like to be able to orient map footprints along x/y axes so view grid during map placement is useful for that

**Comment by ajwinter** [comment]
We discussed in Slack a bit, and landed on displaying a single "reticle" in the middle of the screen in map placement mode (this solves some technical issues with matching up the grid exactly combined with zooming).

Scaling issue is fixed and merged to develop, remaining fixes coming shortly.
