### ISSUE TITLE
Add an "Import Library" button that only adds new library objects (Constructions, Daylighting Controls, Windows)

### ISSUE THREAD

**Issue by ajwinter** [NREL/openstudio-geometry-editor#8]

**Comment by ljbrackney** [comment]
This feature does not appear to work in my build.  Also should space types be imported?  I am importing from the small office prototype model, and seeing no construction sets or space type definitions available for selection.  Either I am misunderstanding the intended functionality or the feature isn't working correctly.

**Comment by devKate** [comment]
What part is not working? Is your library formatted to match the example library at schema/default_library.json?

**Comment by ljbrackney** [comment]
Dan - I tried to use the old "import osm" workflow to strip out definitions.  If that's no longer supported do we have to expose the standards gem json files as input?  The intended workflow isn't clear to me and the editor provided no error message when selecting an osm.

On Jun 15, 2017, at 1:23 PM, Katie Noland <notifications@github.com<mailto:notifications@github.com>> wrote:


What part is not working? Is your library formatted to match the example library at schema/default_library.json?

-
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNREL%2Fopenstudio-geometry-editor%2Fissues%2F8%23issuecomment-308855510&data=02%7C01%7Clarry.brackney%40nrel.gov%7C334b91684df942bb5ca408d4b42c6122%7Ca0f29d7e28cd4f5484427885aee7c080%7C1%7C0%7C636331550082545547&sdata=Q5LyNwvfWNMAiB4tIFXIjQo7%2B0BOOTf1Hed8EWhItZY%3D&reserved=0>, or mute the thread.<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACIHhqpy31pb7PWVyUREJOMMpmr7Twadks5sEZKzgaJpZM4NeZn1&data=02%7C01%7Clarry.brackney%40nrel.gov%7C334b91684df942bb5ca408d4b42c6122%7Ca0f29d7e28cd4f5484427885aee7c080%7C1%7C0%7C636331550082545547&sdata=UykNlDNyoBzdRrPMH5yYPBf%2FMfJWhDVU7qQqhemhEvU%3D&reserved=0>

<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACIHhqpy31pb7PWVyUREJOMMpmr7Twadks5sEZKzgaJpZM4NeZn1&data=02%7C01%7Clarry.brackney%40nrel.gov%7C334b91684df942bb5ca408d4b42c6122%7Ca0f29d7e28cd4f5484427885aee7c080%7C1%7C0%7C636331550082545547&sdata=UykNlDNyoBzdRrPMH5yYPBf%2FMfJWhDVU7qQqhemhEvU%3D&reserved=0>

**Comment by macumber** [comment]
The import library feature does not read OSM, it reads the floorplan.json format.

**Comment by macumber** [comment]
The intent would be to export data from the standards gem to floorplan.json format at some point so you would have a list of space types to choose from in the editor

**Comment by macumber** [comment]
@ljbrackney this script will convert an OSM to a library in JSON format, https://github.com/NREL/openstudio-geometry-editor/blob/master/schema/create_library.rb

You could run this on a prototype model or something to generate a library.json pre-populated with standards space types.  Is that something you can test?

**Comment by macumber** [comment]
@devKate actually could you add an error dialog if you try to upload an invalid file as input?

**Comment by ljbrackney** [comment]
Beautiful!  I shall test!

On Jun 16, 2017, at 11:57 AM, Dan Macumber <notifications@github.com<mailto:notifications@github.com>> wrote:


@ljbrackney<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fljbrackney&data=02%7C01%7Clarry.brackney%40nrel.gov%7C914caa2355824d35480708d4b4e94f81%7Ca0f29d7e28cd4f5484427885aee7c080%7C1%7C0%7C636332361535441578&sdata=M%2Fp6fmV%2Fdt8XOGXjs7%2BdGy3Uvra3D5dK4Xq1eVTTWk0%3D&reserved=0> this script will convert an OSM to a library in JSON format, https://github.com/NREL/openstudio-geometry-editor/blob/master/schema/create_library.rb<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNREL%2Fopenstudio-geometry-editor%2Fblob%2Fmaster%2Fschema%2Fcreate_library.rb&data=02%7C01%7Clarry.brackney%40nrel.gov%7C914caa2355824d35480708d4b4e94f81%7Ca0f29d7e28cd4f5484427885aee7c080%7C1%7C0%7C636332361535441578&sdata=e6LBmn1wAjDQhkC6eHAqBhd7BF3Mac1xU3BgVnRuxuo%3D&reserved=0>

You could run this on a prototype model or something to generate a library.json pre-populated with standards space types. Is that something you can test?

-

**Comment by macumber** [comment]
First check that file is JSON, second list number of objects imported
